# Generated by Django 4.2.6 on 2023-11-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='pera',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
