# Generated by Django 4.2.6 on 2023-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_gallery_pera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='SelectWorkout',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
