# Generated by Django 4.2.6 on 2023-11-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_attendance_selectworkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='TrainedBy',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
