# Generated by Django 4.2.6 on 2023-11-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_attendance_trainedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='SelectWorkout',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='TrainedBy',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
