# Generated by Django 4.2.6 on 2023-11-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_attendance_trainedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='SelectWorkout',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='TrainedBy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
