# Generated by Django 4.2.6 on 2023-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_attendance_selectworkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Gender',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='SelectMembershipplan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='SelectTrainer',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
