# Generated by Django 4.2.6 on 2023-11-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(max_length=200)),
                ('S_title', models.CharField(max_length=200)),
            ],
        ),
    ]
