# Generated by Django 4.2.6 on 2023-11-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_home_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text1', models.TextField(max_length=300)),
                ('text2', models.TextField(max_length=300)),
                ('subtitle1', models.TextField(max_length=200)),
                ('img', models.ImageField(upload_to='home')),
            ],
        ),
        migrations.RemoveField(
            model_name='home_head',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='home_head',
            name='title',
        ),
    ]
