# Generated by Django 4.2.6 on 2023-11-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_home_welcome_remove_home_head_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_welcome',
            name='subtitle2',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home_welcome',
            name='subtitle1',
            field=models.TextField(),
        ),
    ]
